spring.application.name=API-de-Helpdesk
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:helpdeskdb

jwt.secret=YO0ORzTA8DKJv7TYRvAp51RTKGOttn/uX3s6wWsLGWmOUGCHiXcxq2j0w8UntM8A
jwt.access-token-expiration-ms=900000
jwt.refresh-token-expiration-ms=604800000

app.admin.email=admin@helpdesk.com
app.admin.password=Admin123!
