spring.application.name=API-de-Helpdesk
spring.h2.console.enabled=true
spring.datasource.url=${DATABASE_URL}

jwt.secret=${JWT_SECRET}
jwt.access-token-expiration-ms=900000
jwt.refresh-token-expiration-ms=604800000

app.admin.email=admin@helpdesk.com
app.admin.password=${DATABASE_USER}
